const Menu = [
    {
        id: 1,
        image: './images/maggi.png',
        name: 'maggi',
        category: 'breakfast',
        price: 'Rs.12',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 2,
        image: './images/allupaloida.jpg',
        name: 'allu pakoida',
        category: 'evening',
        price: 'Rs.20',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 3,
        image: './images/corn.jpg',
        name: 'corn',
        category: 'breakfast',
        price: 'Rs.10',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 4,
        image: './images/chola.jpg',
        name: 'chola',
        category: 'lunch',
        price: 'Rs.50',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 5,
        image: './images/pizza.jpg',
        name: 'Pizza',
        category: 'evening',
        price: 'Rs.80',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 6,
        image: './images/nonvegthali.jpg',
        name: 'Non-veg thali',
        category: 'dinner',
        price: 'Rs.180',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 7,
        image: './images/sweet.jpg',
        name: 'sweets',
        category: 'dinner',
        price: 'Rs.60',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 8,
        image: './images/rajmarice.jpg',
        name: 'Rajma rice',
        category: 'lunch',
        price: 'Rs.60',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
    {
        id: 9,
        image: './images/samosa.jpg',
        name: 'Samosa',
        category: 'evening',
        price: 'Rs.10',
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
    },
];

export default Menu;